### ISSUE TITLE
Add relevant badges to README

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/ethcontract-rs#18]
- [x] Buid badge (#211)
- [x] docs.rs badge (#213)
- [x] crates.io badge (#213)
- [x] min `rustc` version (#213)
